### ISSUE TITLE
Decide on name of potentially new app format

### ISSUE THREAD

**Issue by LinusCDE** [toltec-dev/organization#10]
Hi,

a successor to the known draft format is currently in the works. For that we **may** need a name in case we don't decide on using  [XDG Desktop Entries](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html).

## How to get involved

**Until Jan 20th 5 PM UTC**, you can propose new names here. Please just comment with a name as a bullet point (prefixed by ` - ` or equivalent) and nothing else.

**Discussions** are supposed to be happening either [in this gh-discussion](https://github.com/toltec-dev/organization/discussions/11) or the IRC channel #remarkable on [freenode](https://freenode.net/) (or matrix/discord the bridges).

Again, **please do not comment or discuss on proposals in this issue**. Use the above means.

**Until Jan 24th 5 PM UTC** will be time for yet more discussion, but no new name. After this the polling phase will start.

**Until Jan 28th 3 PM UTC** will be the time to give your decision on what name you like. I'll add a link to a poll here and announce it in the IRC as well.

## Final poll options

*Will be listed here on Jan 20th 5 PM UTC*

## Poll

*Will be listed here on Jan 24th 5 PM UTC and available until until Jan 28th 3 PM UTC.* I'll likely publish the results here as well.

**Comment by LinusCDE** [comment]
- rmapp
- inklet

**Comment by alistair23** [comment]
+1 on following the https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

It matches the Gnome format as well: https://developer.gnome.org/desktop-entry-spec/

Which means we can standardise on a common format (instead of inventing something new)

**Comment by siraben** [comment]
_amatl_ is the Nahuatl word for paper[0]

[0] https://en.wikipedia.org/wiki/Amate

**Comment by LinusCDE** [comment]
Missed that the deadline was 24th and not 25th. [Here is the poll](https://cloud.cosmos-ink.net/apps/polls/s/rAQp1Qmr865Eydrn). The name doesn't really matter (I can't seem to turn it off).

Results will be visible at Jan 28th 3 PM UTC. I can enable the results earlier, but don't want to have a few first votes affect the decisions of others.

**Comment by LinusCDE** [comment]
The poll was closed. 22 people participated and *Inklet* won.

![grafik](https://user-images.githubusercontent.com/22298664/106184853-614d8a80-61a2-11eb-96c8-e96e6a61e401.png)

Because of the "maybe" option there are several views to count the vote. All of them have the same result though:

![grafik](https://user-images.githubusercontent.com/22298664/106184984-8e01a200-61a2-11eb-9868-7302ecc1350a.png)
