### ISSUE TITLE
Revisit XDG .desktop files

### ISSUE THREAD

**Issue by danshick** [toltec-dev/organization#3]
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

It would be nice to consume an existing standard. Hopefully this issue can serve as a place to persist information on why or why not XDG desktop files might be a good fit.

Importantly, I think it is worth mentioning that there are two mechanisms to extend the recognized keys supported by the format:

> **Extending the format**
> 
> If the standard is to be amended with a new {key,value} pair which should be applicable to all supporting parties, a group discussion will take place. This is the preferred method for introducing changes. If one particular party wishes to add a field for personal use, they should prefix the key with the string X-PRODUCT, e.g. X-NewDesktop-Foo, following the precedent set by other IETF and RFC standards.
> 
> Alternatively, fields can be placed in their own group, where they may then have arbitrary key names. If this is the case, the group should follow the scheme outlined above, i.e. [X-PRODUCT GROUPNAME] or something similar. These steps will avoid namespace clashes between different yet similar environments.

**Comment by Eeems** [comment]
Would we also want to support `xdg-open` and the [MIME Applications spec](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html)?

**Comment by coozoo** [comment]
vote plus for desktop entry files well developed, it's easy to read, easy to capture in bash, easy to edit with text editor..
no need creepy yaml, no need sophisticated json structure

**Comment by Eeems** [comment]
creepy yaml? sophisticated json?

**Comment by coozoo** [comment]
> creepy yaml? sophisticated json?

do you think it's not creepy to follow all indentations with text editor (I'm not talking about text processors or complete IDE). I should mention it's IMHO :)
I've just tried to setup github actions and simply screwed up with space at the end of string and wondered why nothing work.

About json, try to read it without jq from cosole :)

**Comment by Eeems** [comment]
> 
> 
> > creepy yaml? sophisticated json?
> 
> do you think it's not creepy to follow all indentations with text editor (I'm not talking about text processors or complete IDE). I should mention it's IMHO :)
> I've just tried to setup github actions and simply screwed up with space at the end of string and wondered why nothing works.

I've done a lot of python programming, so whitespace stuff doesn't bother me.

> 
> About json, try to read it without jq from console :)

Why? That's what `jq` is there for. Just like you don't try to read image files directly from the console ;)

**Comment by coozoo** [comment]
> I've done a lot of python programming, so whitespace stuff doesn't bother me.

Yeah I know ppl like you 😏 my eyes are bleeding when I'm editing python files with mcedit :)
 
> Why? That's what `jq` is there for. Just like you don't try to read image files directly from the console ;)

there is small difference. Image files content is "binary", json still text and there is cases when you need to parse it directly :)

**Comment by Eeems** [comment]
> mcedit

There's your problem ;)

> there is small difference. Image files content is "binary", json still text and there is cases when you need to parse it directly :)

Wouldn't using jq still be a better option? I'm failing to see a scenario that you'd need to parse it directly.

**Comment by coozoo** [comment]
> Wouldn't using jq still be a better option? I'm failing to see a scenario that you'd need to parse it directly.

jq usually needs to be installed it's not a part of posix. and remarkable by default without it as most of the systems.

**Comment by Eeems** [comment]
Right, but that's up to the application to list as a dependency and either require through toltec, or link to a binary.

**Comment by Eeems** [comment]
In theory desktop files should be easy to work with in Qt: https://gist.github.com/zester/1185753

**Comment by coozoo** [comment]
yeah it's not just in theory, it's really easy :)  I can confirm, I'm not using it for desktop files. But I'm using QSettings often for app settings basically the same ini format. 
I think it's more complicate to support features that they provide, like mime or translations sure if there is plans to implement them at all :)

**Comment by Eeems** [comment]
> But I'm using QSettings often for app settings basically the same ini format.

Same here, reMarkable is as well.

> I think it's more complicate to support features that they provide, like mime or translations sure if there is plans to implement them at all :)

Yeah, we'd probably just want to support a subset initially.

**Comment by matteodelabre** [comment]
Python also provides easy support for ini-like files. Could be handy for generating compat Draft & Oxide files from a Python script.

https://docs.python.org/3/library/configparser.html

**Comment by coozoo** [comment]
here it's an old qt4 project there was some implementation maybe it can be helpful despite it for qt4
https://github.com/radekp/qtmoko/blob/cdaa420a6675aa396c326b07122a853a9d5578a8/src/3rdparty/applications/qx/DesktopScanner.cpp

https://doc.qt.io/archives/qtextended4.4/desktopfiles.html

**Comment by raisjn** [comment]
> One issue with using .desktop files is that existing applications in the *nix ecosystem use them, but expect to be running under X or Wayland. Since we currently are not working towards implementing either, it does cause some problems with having application entries show up that will never run.

from the spec:

> This specification defines 3 types of desktop entries: Application (type 1), Link (type 2) and Directory (type 3). To allow the addition of new types in the future, implementations should ignore desktop entries with an unknown type.

**Comment by Eeems** [comment]
Do they allow custom types though, or are they assuming that new types should only be added by the official spec?

**Comment by danshick** [comment]
> Do they allow custom types though, or are they assuming that new types should only be added by the official spec?

Even of we don't create a new type, we should probably define a custom group for all of our unofficial settings. The spec suggests the format `[X-PRODUCT GROUPNAME]` so maybe `[X-Remarkable Settings]`.

If that group were missing, we could ignore the file. Also, we could even have a `launchable` setting in there. There are some toltec apps that shouldn't be listed by the launcher, like the restream binary.

**Comment by Eeems** [comment]
> Even of we don't create a new type, we should probably define a custom group for all of our unofficial settings. The spec suggests the format `[X-PRODUCT GROUPNAME]` so maybe `[X-Remarkable Settings]`.

I'd probably define one for all of the Oxide specific settings as well.

> If that group were missing, we could ignore the file. Also, we could even have a `launchable` setting in there. There are some toltec apps that shouldn't be listed by the launcher, like the restream binary.

I think that ignoring everything without `[X-reMarkable Settings]` is a good idea. As for a launchable setting, likely not. If it's defining a desktop file, it's telling launchers that it can be launched. Otherwise it should just not define a file.

**Comment by matteodelabre** [comment]
> Do they allow custom types though, or are they assuming that new types should only be added by the official spec?

As discussed during our meeting, it seems that the specification mandates parsers to allow for types other than the three currently documented ones. The concern voiced by @Eeems was that a future update of the standard could add a new type that happens to conflict with ours. Note that the standard recommends that custom _field names_ be prefixed with `X-ProductName`. I think we could apply this recommendation to make a custom type. For example, it is pretty unlikely that a future extension would reserve the `Type=X-reMarkable-app` value.

**Comment by danshick** [comment]
I think we can stick to existing types for the predefined fields and run wild as long as we stick to our own X-Remarkable fields and groups.

Are there any standardized fields where a preexisting type doesn't fit for us?

**Comment by raisjn** [comment]
> I think we can stick to existing types for the predefined fields and run wild as long as we stick to our own X-Remarkable fields and groups.
> 
> Are there any standardized fields where a preexisting type doesn't fit for us?

i believe systemd service files uses repeated keys for arrays, which i'm not sure is in this spec. additionally, there's no map type in this spec.

**Comment by Eeems** [comment]
For arrays I guess we can go with space or comma delimited.
We could emulate maps with the following though:
```ini
Map[Field0]=Value0
Map[Field1]=Value1
```

**Comment by danshick** [comment]
```
Some keys can have multiple values. In such a case, the value of the key is specified as a plural: for example, string(s). The multiple values should be separated by a semicolon and the value of the key may be optionally terminated by a semicolon. Trailing empty strings must always be terminated with a semicolon. Semicolons in these values need to be escaped using \;. 
```
