### ISSUE TITLE
Define security policy

### ISSUE THREAD

**Issue by Eeems** [toltec-dev/organization#6]
We currently don't have a security policy defined. Before "going live" we should probably define that.

**Comment by danshick** [comment]
> > How do people report vulnerabilities in toltec? By opening an issue in the repository? By sending an email to security@...?
> 
> I think we should have an email option for egregious security vulnerabilities, otherwise an issue makes sense. As for who the email goes to, that I'm not sure.

security@toltec-dev.org -> script to dump emails into a special discord thread?
